test: migrate clang-tidy to LLVM 18 (#5497)
* build: install newer dependencies

* build: only build as plugin not executable

since i don't think anyone's using executable and plugin is sufficient

* build: vendor check_clang_tidy.py

* build: fix headers, errors, warnings

* chore: script to get affected files

* ci: gather affected files

* test: run clang-tidy with plugins

* ci: show most time-consuming job

see: https://github.com/CleverRaven/Cataclysm-DDA/pull/64648

co-authored-by: Binrui Dong <brett.browning.dong@gmail.com>

* test: exclude problemetic checks

bugprone-unchecked-optional-access: https://github.com/llvm/llvm-project/issues/111003
bugprone-chained-comparison: conflicts with catch2
clang-diagnostic-unused-macros: https://github.com/llvm/llvm-project/issues/59572
clang-analyzer-optin: segfaults

* refactor: remove unneeded CATA_CLANG_TIDY logic

building clang-tidy is handled separatedly on build-clang-tidy-plugin.sh

* fix: run a lint as an example

* docs: update how to build clang-tidy plugin

---------

Co-authored-by: nocontribute <>
Co-authored-by: Binrui Dong <brett.browning.dong@gmail.com>

diff --git a/.github/workflows/clang-tidy.yml b/.github/workflows/clang-tidy.yml
--- a/.github/workflows/clang-tidy.yml
+++ b/.github/workflows/clang-tidy.yml
@@ -1,9 +1,9 @@
-name: Clang-tidy (clang-12, tiles)
+name: Clang-tidy (tiles)
 
 on:
-  push:
-    branches: [main]
-    paths: [ "**.cpp", "**.h", "**.c", "**/CMakeLists.txt", "**/Makefile", "**.hpp", "**.cmake", "build-scripts/**","tools/clang-tidy-plugin/**", ".github/workflows/clang-tidy.yml", "**/.clang-tidy" ]
+  # push:
+  #   branches: [main]
+  #   paths: [ "**.cpp", "**.h", "**.c", "**/CMakeLists.txt", "**/Makefile", "**.hpp", "**.cmake", "build-scripts/**","tools/clang-tidy-plugin/**", ".github/workflows/clang-tidy.yml", "**/.clang-tidy" ]
   pull_request:
     branches: [main]
     paths: [ "**.cpp", "**.h", "**.c", "**/CMakeLists.txt", "**/Makefile", "**.hpp", "**.cmake", "build-scripts/**", "tools/clang-tidy-plugin/**", ".github/workflows/clang-tidy.yml", "**/.clang-tidy" ]
@@ -16,7 +16,7 @@ concurrency:
 jobs:
   skip-duplicates:
     continue-on-error: true
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-24.04
     # Map a step output to a job output
     outputs:
       should_skip: ${{ steps.skip_check.outputs.should_skip }}
@@ -30,28 +30,48 @@ jobs:
     needs: skip-duplicates
     if: ${{ needs.skip-duplicates.outputs.should_skip != 'true' }}
 
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-24.04
     env:
       CMAKE: 1
-      CLANG: clang++-12
-      COMPILER: clang++-12
-      CATA_CLANG_TIDY: plugin
+      CLANG: /usr/bin/clang++-18
+      COMPILER: /usr/bin/clang++-18
       TILES: 1
       SOUND: 1
+      BUILD_PATH: "build"
+      AFFECTED_FILES: "affected_files.txt"
 
     steps:
       - name: checkout repository
         uses: actions/checkout@v4
-        with:
-          fetch-depth: 1
+
       - name: install dependencies
         run: |
-          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
-          sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main"
           sudo apt-get update
-          sudo apt-get install libncursesw5-dev clang-12 libclang-12-dev llvm-12-dev llvm-12-tools \
-            libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev libpulse-dev ccache \
-            libflac-dev gettext
+          sudo apt-get install \
+            cmake gettext ninja-build mold ccache jq \
+            clang-18 libclang-18-dev llvm-18 llvm-18-dev clang-tidy-18 \
+            libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev libpulse-dev libflac-dev
+
+      - name: ensure clang 18 is installed
+        run: |
+          if [ -z "$(command -v clang++-18)" ]; then
+            echo "clang 18 not found"
+            exit 1
+          fi
+          ls -al /usr/lib/llvm-18/lib
+          if [ ! -d /usr/lib/llvm-18/lib ]; then
+            echo "llvm-18 not found"
+            exit 1
+          fi
+
+          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100
+          sudo update-alternatives --install /usr/bin/FileCheck FileCheck /usr/bin/FileCheck-18 100
+
+      - name: Setup ccache
+        uses: Chocobo1/setup-ccache-action@v1
+        with:
+          install_ccache: false
+          update_packager_index: false
 
       - name: add problem matcher
         run: |
@@ -60,8 +80,34 @@ jobs:
           echo "::add-matcher::build-scripts/problem-matchers/catch2.json"
           echo "::add-matcher::build-scripts/problem-matchers/debugmsg.json"
 
-      - name: prepare
-        run: bash ./build-scripts/requirements.sh
       - uses: ammaraskar/gcc-problem-matcher@master
+
+      - uses: denoland/setup-deno@v1
+        with:
+          deno-version: v1.x
+
+      - name: build clang-tidy plugin
+        run: |
+          pip install --break-system-packages lit
+          bash ./build-scripts/build-clang-tidy-plugin.sh
+
+      # - name: test clang-tidy plugin
+      #   run: |
+      #     lit -v $BUILD_PATH/tools/clang-tidy-plugin/test
+      #     clang-tidy --version
+
+      - name: gather affected files
+        run: deno task affected-files ${{ github.event.pull_request.number }} --output "$AFFECTED_FILES"
+
       - name: run clang-tidy
-        run: bash ./build-scripts/build.sh
+        run: bash ./build-scripts/run-clang-tidy-plugin.sh
+
+      - name: show most time consuming checks
+        if: always()
+        run: | # the folder may not exist if there is no file to analyze
+          if [ -d clang-tidy-trace ]
+          then
+            jq -n 'reduce(inputs.profile | to_entries[]) as {$key,$value} ({}; .[$key] += $value) | with_entries(select(.key|contains(".wall"))) | to_entries | sort_by(.value) | reverse | .[0:10] | from_entries' clang-tidy-trace/*.json
+          else
+            echo "clang-tidy-trace folder not found."
+          fi
