ci: skip via either code or data
see:
- https://github.com/CleverRaven/Cataclysm-DDA/commit/57077421c783a629ee2429cdbf2252feac3dae20
- https://github.com/CleverRaven/Cataclysm-DDA/commit/f6ec25f9e471a4216fe6a7f9f2f7ac60a8d611cd

Co-authored-by: Kevin Granade <kevin.granade@gmail.com>
Co-authored-by: Andrew Krieger <akrieger@users.noreply.github.com>

diff --git a/.github/workflows/matrix.yml b/.github/workflows/matrix.yml
--- a/.github/workflows/matrix.yml
+++ b/.github/workflows/matrix.yml
@@ -23,21 +23,51 @@ concurrency:
   cancel-in-progress: ${{ github.event_name == 'pull_request' }}
 
 jobs:
-  skip-duplicates:
+  skip-duplicates-code:
     continue-on-error: true
     runs-on: ubuntu-22.04
     # Map a step output to a job output
     outputs:
-      should_skip: ${{ steps.skip_check.outputs.should_skip }}
+      should_skip_code: ${{ steps.skip_check.outputs.should_skip }}
     steps:
       - id: skip_check
         uses: fkirc/skip-duplicate-actions@master
         with:
-          cancel_others: "true"
-          paths_ignore: '["android/**", "build-data/osx/**", "doc/**", "doxygen_doc/**", "lgtm/**", "msvc-**", "object_creator/**", "tools/**", "utilities/**"]'
+          paths_ignore: '["android/**", "build-data/osx/**", "doc/**", "doxygen_doc/**", "msvc-**", "object_creator/**", "tools/**", "utilities/**", "scripts/**", "data/**", "lang/**"]'
+
+  skip-duplicates-data:
+    continue-on-error: true
+    runs-on: ubuntu-22.04
+    # Map a step output to a job output
+    outputs:
+      should_skip_data: ${{ steps.skip_check.outputs.should_skip }}
+    steps:
+      - id: skip_check
+        uses: fkirc/skip-duplicate-actions@master
+        with:
+          paths_ignore: '["android/**", "build-data/osx/**", "doc/**", "doxygen_doc/**", "msvc-**", "object_creator/**", "tools/**", "utilities/**", "scripts/**"]'
+
+  matrix-variables:
+    permissions:
+      contents: none
+    continue-on-error: true
+    runs-on: ubuntu-latest
+    outputs:
+      fail_fast: ${{ steps.matrix_vars.outputs.fail_fast }}
+      skip_tests: ${{ steps.matrix_vars.outputs.skip_tests }}
+      max_parallel: ${{ steps.matrix_vars.outputs.max_parallel }}
+    steps:
+      - id: matrix_vars
+        run: |
+          echo "fail_fast=$([ "$GITHUB_REF_NAME" = "upload" ] && echo false || echo true)" >> $GITHUB_OUTPUT
+          echo "skip_tests=$([ "$GITHUB_REF_NAME" = "upload" ] && echo true || echo false)" >> $GITHUB_OUTPUT
+          echo "max_parallel=$([ "$GITHUB_REF_NAME" = "upload" ] && echo 20 || echo 1)" >> $GITHUB_OUTPUT
+
   varied_builds:
-    needs: skip-duplicates
+    needs: [ skip-duplicates-code, skip-duplicates-data, matrix-variables ]
     strategy:
+      fail-fast: ${{ fromJSON(needs.matrix-variables.outputs.fail_fast) }}
+      max-parallel: ${{ fromJSON(needs.matrix-variables.outputs.max_parallel) }}
       matrix:
         include:
           - title: GCC 12, Ubuntu, Curses
@@ -131,12 +161,14 @@ jobs:
       LIBBACKTRACE: ${{ matrix.libbacktrace }}
       NATIVE: ${{ matrix.native }}
       RELEASE: 1
-      SKIP: ${{ needs.skip-duplicates.outputs.should_skip == 'true' }}
 
       CCACHE_LIMIT: ${{ matrix.ccache_limit }}
       CCACHE_FILECLONE: true
       CCACHE_HARDLINK: true
       CCACHE_NOCOMPRESS: true
+
+      SKIP: ${{ ( github.event.pull_request.draft == true && matrix.title != 'GCC 12, Ubuntu, Curses' ) || ( needs.skip-duplicates-code.outputs.should_skip_code == 'true' ) || ( needs.skip-duplicates-data.outputs.should_skip_data == 'true' ) }}
+      SKIP_TESTS: ${{ needs.matrix-variables.outputs.skip_tests }}
 
     steps:
       - name: checkout repository
@@ -168,7 +200,7 @@ jobs:
         if: ${{ env.SKIP == 'false' && runner.os == 'macOS' }}
         run: |
           HOMEBREW_NO_AUTO_UPDATE=yes HOMEBREW_NO_INSTALL_CLEANUP=yes brew install sdl2 sdl2_image sdl2_ttf sdl2_mixer gettext ccache parallel
-          
+
       - name: prepare
         if: ${{ env.SKIP == 'false' }}
         run: bash ./build-scripts/requirements.sh
